spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
---
server:
  port: @server.port@
---
restTemplate:
  networkTimeout: 3000
---
converterIp:
  nat64prefix: "2a04:4a00:5:10ff:4:1:"
---
restTemplate:
  connectTimeout: 3000
  connectionRequestTimeout: 60000
  readTimeout: 60000
---
starrys:
  url: "https://fce.starrys.ru:4443/fr/api/v2/"
